### PR TITLE
Added Prettier Formatting into the Github CICD Actions

### PR DESCRIPTION
**Pull request by SamyakJain2020**

### CODE REVIEW

**Comment by SamyakJain2020** [comment]
@officialpiyush Please Do the QA

**Review by whopiyush — CHANGES_REQUESTED** [review]
can you correct the folder structure of the action,  you  may refer to [the documentation](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#adding-an-action-from-the-same-repository)

**Comment by SamyakJain2020** [comment]
ok Will do

**Review by whopiyush — APPROVED** [review]
looks good

**Pull request merged**
